[supervisord]
nodaemon=true

[program:daphne]
command=daphne -b 0.0.0.0 -p 8080 sentinel.asgi:application
startsecs=10
autorestart=true

[program:celery]
command=celery -A sentinel worker -E --loglevel INFO --without-heartbeat --without-mingle --without-gossip
startsecs=10
autorestart=true
