# Generated by Django 5.1.2 on 2024-10-29 03:08

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordSetupToken",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "next_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to redirect to after password setup",
                        null=True,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("setup", "Setup Password"),
                            ("reset", "Reset Password"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Token",
                "verbose_name_plural": "Password Tokens",
            },
        ),
    ]
