# Generated by Django 5.1.2 on 2024-10-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_passwordsetuptoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordsetuptoken",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
