# Generated by Django 5.1.2 on 2024-11-01 04:04

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementToken",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="secret"
                    ),
                ),
                (
                    "issued_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Issued On"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expiration Date")),
                ("revoked", models.BooleanField(default=False, verbose_name="Revoked")),
            ],
            options={
                "verbose_name": "Management Token",
                "verbose_name_plural": "Management Tokens",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to="oidc_provider/organizations",
                        verbose_name="Logo Image",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "website_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Website URL",
                    ),
                ),
                (
                    "terms_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External reference to the privacy policy of the client.",
                        max_length=255,
                        verbose_name="Terms URL",
                    ),
                ),
                (
                    "contact_email",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        default=False,
                        help_text="Set this connection as default.",
                        verbose_name="Default",
                    ),
                ),
                (
                    "post_password_update_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Redirect URL after password update.",
                        max_length=255,
                        verbose_name="Post Password Update URL",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResponseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("code", "code (Authorization Code Flow)"),
                            ("id_token", "id_token (Implicit Flow)"),
                            ("id_token token", "id_token token (Implicit Flow)"),
                            ("code token", "code token (Hybrid Flow)"),
                            ("code id_token", "code id_token (Hybrid Flow)"),
                            (
                                "code id_token token",
                                "code id_token token (Hybrid Flow)",
                            ),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Response Type Value",
                    ),
                ),
                ("description", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RSAKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.TextField(
                        help_text="Paste your private RSA Key here.", verbose_name="Key"
                    ),
                ),
            ],
            options={
                "verbose_name": "RSA Key",
                "verbose_name_plural": "RSA Keys",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="Name"),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("confidential", "Confidential"),
                            ("public", "Public"),
                        ],
                        default="confidential",
                        help_text="<b>Confidential</b> clients are capable of maintaining the confidentiality of their credentials. <b>Public</b> clients are incapable.",
                        max_length=30,
                        verbose_name="Client Type",
                    ),
                ),
                (
                    "client_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Client ID",
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Client SECRET"
                    ),
                ),
                (
                    "jwt_alg",
                    models.CharField(
                        choices=[("HS256", "HS256"), ("RS256", "RS256")],
                        default="RS256",
                        help_text="Algorithm used to encode ID Tokens.",
                        max_length=10,
                        verbose_name="JWT Algorithm",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(auto_now_add=True, verbose_name="Date Created"),
                ),
                (
                    "website_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Website URL",
                    ),
                ),
                (
                    "terms_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External reference to the privacy policy of the client.",
                        max_length=255,
                        verbose_name="Terms URL",
                    ),
                ),
                (
                    "contact_email",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to="oidc_provider/clients",
                        verbose_name="Logo Image",
                    ),
                ),
                (
                    "reuse_consent",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, server will save the user consent given to a specific client, so that user won't be prompted for the same authorization multiple times.",
                        verbose_name="Reuse Consent?",
                    ),
                ),
                (
                    "require_consent",
                    models.BooleanField(
                        default=True,
                        help_text="If disabled, the Server will NEVER ask the user for consent.",
                        verbose_name="Require Consent?",
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=False,
                        help_text="Allow new user registration.",
                        verbose_name="Allow Registration",
                    ),
                ),
                (
                    "_redirect_uris",
                    models.TextField(
                        default="",
                        help_text="Enter each URI on a new line.",
                        verbose_name="Redirect URIs",
                    ),
                ),
                (
                    "_post_logout_redirect_uris",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Enter each URI on a new line.",
                        verbose_name="Post Logout Redirect URIs",
                    ),
                ),
                (
                    "_scope",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Specifies the authorized scope values for the client app.",
                        verbose_name="Scopes",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oidc_clients_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "response_types",
                    models.ManyToManyField(to="oidc_provider.responsetype"),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="IdentityProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("google-oauth2", "Google"),
                            ("microsoft-graph", "Microsoft"),
                        ],
                        max_length=30,
                        verbose_name="Provider",
                    ),
                ),
                ("configuration", models.JSONField(verbose_name="Configuration")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_providers",
                        to="oidc_provider.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity Provider",
                "verbose_name_plural": "Identity Providers",
                "unique_together": {("organization", "type")},
            },
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expiration Date")),
                ("_scope", models.TextField(default="", verbose_name="Scopes")),
                (
                    "code",
                    models.CharField(max_length=255, unique=True, verbose_name="Code"),
                ),
                (
                    "nonce",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Nonce"
                    ),
                ),
                (
                    "is_authentication",
                    models.BooleanField(
                        default=False, verbose_name="Is Authentication?"
                    ),
                ),
                (
                    "code_challenge",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Code Challenge"
                    ),
                ),
                (
                    "code_challenge_method",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Code Challenge Method"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oidc_provider.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oidc_provider.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authorization Code",
                "verbose_name_plural": "Authorization Codes",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expiration Date")),
                ("_scope", models.TextField(default="", verbose_name="Scopes")),
                (
                    "access_token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Access Token"
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Refresh Token"
                    ),
                ),
                ("_id_token", models.TextField(verbose_name="ID Token")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oidc_provider.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oidc_provider.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or Disable this connection.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "_email_domains",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Enter each domain on a new line.",
                        verbose_name="Email Domains",
                    ),
                ),
                (
                    "enable_mfa",
                    models.BooleanField(
                        default=False,
                        help_text="Enable Multi-Factor Authentication for this connection.",
                        verbose_name="Enable MFA",
                    ),
                ),
                (
                    "prevent_auth",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent user authentication if at least user role not in grants.",
                        verbose_name="Prevent Auth",
                    ),
                ),
                (
                    "include_roles",
                    models.BooleanField(
                        default=False,
                        help_text="Include user roles in id_token.",
                        verbose_name="Include Roles",
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=False,
                        help_text="Allow new user registration.",
                        verbose_name="Allow Registration",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="oidc_provider.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "grants",
                    models.ManyToManyField(to="auth.group", verbose_name="Grants"),
                ),
                (
                    "identity_providers",
                    models.ManyToManyField(
                        blank=True,
                        to="oidc_provider.identityprovider",
                        verbose_name="Identity Providers",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="oidc_provider.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "organization")},
            },
        ),
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, to="auth.group", verbose_name="Roles"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="oidc_provider.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expiration Date")),
                ("_scope", models.TextField(default="", verbose_name="Scopes")),
                ("date_given", models.DateTimeField(verbose_name="Date Given")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oidc_provider.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oidc_provider.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Consent",
                "verbose_name_plural": "User Consents",
                "unique_together": {("user", "client", "organization")},
            },
        ),
    ]
