# Generated by Django 5.1.2 on 2024-10-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_provider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationIdentityProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("google-oauth2", "Google"),
                            ("microsoft-graph", "Microsoft"),
                        ],
                        max_length=30,
                        verbose_name="Provider",
                    ),
                ),
                ("configuration", models.JSONField(verbose_name="Configuration")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_providers",
                        to="oidc_provider.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
        ),
    ]
