# Generated by Django 5.1.2 on 2024-10-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_provider", "0002_organizationidentityprovider"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="identity_providers",
            field=models.ManyToManyField(
                blank=True,
                to="oidc_provider.organizationidentityprovider",
                verbose_name="Identity Providers",
            ),
        ),
    ]
