# Generated by Django 5.1.2 on 2024-10-28 03:42

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_provider", "0002_alter_userconsent_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementAccessToken",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Opaque Token"
                    ),
                ),
                (
                    "issued_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Issued On"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expiration Date")),
                ("revoked", models.BooleanField(default=False, verbose_name="Revoked")),
            ],
            options={
                "verbose_name": "Management Access Token",
                "verbose_name_plural": "Management Access Tokens",
            },
        ),
    ]
