# Generated by Django 5.1.2 on 2024-10-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_provider", "0003_managementaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationuser",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
