# Generated by Django 5.1.2 on 2024-10-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_provider", "0003_connection_identity_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="allow_registration",
            field=models.BooleanField(
                default=False,
                help_text="Allow new user registration.",
                verbose_name="Allow Registration",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationidentityprovider",
            unique_together={("organization", "type")},
        ),
    ]
