# Generated by Django 5.1.2 on 2024-10-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_provider", "0004_organizationuser_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managementaccesstoken",
            name="token",
            field=models.CharField(max_length=128, unique=True, verbose_name="secret"),
        ),
    ]
