# Generated by Django 5.1.2 on 2024-10-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_provider", "0005_alter_managementaccesstoken_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="post_password_update_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Redirect URL after password update.",
                max_length=255,
                verbose_name="Post Password Update URL",
            ),
        ),
    ]
