# Generated by Django 5.1.2 on 2024-10-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_provider", "0006_connection_post_password_update_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection",
            name="post_password_update_url",
        ),
    ]
